services:
  AQ2-pickup:
    build:
      context: .
      dockerfile: Dockerfile
    image: aq2pickup/discordbot
    container_name: AQ2-pickup-bot
    stdin_open: true
    tty: true
    restart: on-failure:4
    env_file:
     - Insert your .env file here
